# Generated by Django 3.0.1 on 2020-01-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20191231_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(null=True, upload_to='images')),
                ('first_image', models.ImageField(null=True, upload_to='images')),
                ('second_image', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'db_table': 'tbl_photo',
            },
        ),
    ]
